config/routes.rb
Rails.application.routes.draw do
  get 'work_space/index'

  get 'sign_up/index'

  get 'welcome/index'
  root 'welcome#index'
  
  post 'sign_up/create'

  resources :correctnesses
  resources :users
  resources :dictionaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/correctness.rb
class Correctness < ApplicationRecord
  belongs_to :dictionary
  belongs_to :user
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/correctnesses_controller.rb
class CorrectnessesController < ApplicationController
  before_action :set_correctness, only: [:show, :edit, :update, :destroy]

  # GET /correctnesses
  # GET /correctnesses.json
  def index
    @correctnesses = Correctness.all
  end

  # GET /correctnesses/1
  # GET /correctnesses/1.json
  def show
  end

  # GET /correctnesses/new
  def new
    @correctness = Correctness.new
  end

  # GET /correctnesses/1/edit
  def edit
  end

  # POST /correctnesses
  # POST /correctnesses.json
  def create
    @correctness = Correctness.new(correctness_params)

    respond_to do |format|
      if @correctness.save
        format.html { redirect_to @correctness, notice: 'Correctness was successfully created.' }
        format.json { render :show, status: :created, location: @correctness }
      else
        format.html { render :new }
        format.json { render json: @correctness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /correctnesses/1
  # PATCH/PUT /correctnesses/1.json
  def update
    respond_to do |format|
      if @correctness.update(correctness_params)
        format.html { redirect_to @correctness, notice: 'Correctness was successfully updated.' }
        format.json { render :show, status: :ok, location: @correctness }
      else
        format.html { render :edit }
        format.json { render json: @correctness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /correctnesses/1
  # DELETE /correctnesses/1.json
  def destroy
    @correctness.destroy
    respond_to do |format|
      format.html { redirect_to correctnesses_url, notice: 'Correctness was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_correctness
      @correctness = Correctness.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def correctness_params
      params.require(:correctness).permit(:dictionary_id, :user_id, :totalTryCount, :rightCount)
    end
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
      params.require(:dictionary).permit(:word, :partOfSpeech, :definition, :wordUsage)
    end
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  def index
    @user = User.new
  end
  
  def create
    @dictionaries = Dictionary.all
    
    redirect_to :controller => 'work_space', :action => 'index'
  
    # render plain: params[:user].inspect
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstName, :lastName, :rights)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/work_space_controller.rb
class WorkSpaceController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/correctnesses_helper.rb
module CorrectnessesHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_space_helper.rb
module WorkSpaceHelper
end

app/views/correctnesses/_form.html.erb
<%= form_for(correctness) do |f| %>
  <% if correctness.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(correctness.errors.count, "error") %> prohibited this correctness from being saved:</h2>

      <ul>
      <% correctness.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dictionary_id %>
    <%= f.text_field :dictionary_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :totalTryCount, 'Total Tried Count' %>
    <%= f.number_field :totalTryCount %>
  </div>

  <div class="field">
    <%= f.label :rightCount, 'Right Count' %>
    <%= f.number_field :rightCount %>
  </div>

  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/correctnesses/edit.html.erb
<h1>Editing Correctness</h1>

<%= render 'form', correctness: @correctness %>

<%= link_to 'Show', @correctness %> |
<%= link_to 'Back', correctnesses_path %>

app/views/correctnesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Correctnesses</h1>

<table class="simple">
  <thead>
    <tr>
      <th>Dictionary</th>
      <th>User</th>
      <th>Total Tries Count</th>
      <th>Right Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @correctnesses.each do |correctness| %>
      <tr>
        <td><%= correctness.dictionary_id %></td>
        <td><%= correctness.user_id %></td>
        <td><%= correctness.totalTryCount %></td>
        <td><%= correctness.rightCount %></td>
        <td><%= link_to 'Show', correctness %></td>
        <td><%= link_to 'Edit', edit_correctness_path(correctness) %></td>
        <td><%= link_to 'Destroy', correctness, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Correctness', new_correctness_path %>

app/views/correctnesses/new.html.erb
<h1>New Correctness</h1>

<%= render 'form', correctness: @correctness %>

<%= link_to 'Back', correctnesses_path %>

app/views/correctnesses/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Correctness</h1>

<p>
  <strong>Dictionary Id:</strong>
  <%= @correctness.dictionary_id %>
</p>

<p>
  <strong>User Id:</strong>
  <%= @correctness.user_id %>
</p>

<p>
  <strong>Total Tried Count:</strong>
  <%= @correctness.totalTryCount %>
</p>

<p>
  <strong>Right Count:</strong>
  <%= @correctness.rightCount %>
</p>

<%= link_to 'Edit', edit_correctness_path(@correctness) %> |
<%= link_to 'Back', correctnesses_path %>

app/views/dictionaries/_form.html.erb
<%= form_for(dictionary) do |f| %>
  <% if dictionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</h2>

      <ul>
      <% dictionary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %>
    <%= f.text_field :word %>
  </div>

  <div class="field">
    <%= f.label :partOfSpeech, 'Part of Speech' %>
    <%= f.text_field :partOfSpeech %>
  </div>

  <div class="field">
    <%= f.label :definition %>
    <%= f.text_area :definition, cols: "100", rows: "5" %>
  </div>

  <div class="field">
    <%= f.label :wordUsage, 'Word Usage' %>
    <%= f.text_area :wordUsage, cols: "100", rows: "10"  %>
  </div>

  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/dictionaries/edit.html.erb
<h1>Editing Dictionary</h1>

<%= render 'form', dictionary: @dictionary %>

<%= link_to 'Show', @dictionary %> |
<%= link_to 'Back', dictionaries_path %>

app/views/dictionaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dictionary</h1>

<table class="simple" >
  <thead>
    <tr>
      <th>Word</th>
      <th>Part of Speech</th>
      <th>Definition</th>
      <th>Word Usage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dictionaries.each do |dictionary| %>
      <tr>
        <td><%= dictionary.word %></td>
        <td><%= dictionary.partOfSpeech %></td>
        <td><%= dictionary.definition %></td>
        <td><%= dictionary.wordUsage %></td>
        <td><%= link_to 'Show', dictionary %></td>
        <td><%= link_to 'Edit', edit_dictionary_path(dictionary) %></td>
        <td><%= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dictionary', new_dictionary_path %>

app/views/dictionaries/new.html.erb
<h1>New Dictionary</h1>

<%= render 'form', dictionary: @dictionary %>

<%= link_to 'Back', dictionaries_path %>

app/views/dictionaries/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Dictionary</h1>

<p>
  <strong>Id:</strong>
  <%= @dictionary.id %>
</p>

<p>
  <strong>Word:</strong>
  <%= @dictionary.word %>
</p>

<p>
  <strong>Part of Speech:</strong>
  <%= @dictionary.partOfSpeech %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @dictionary.definition %>
</p>

<p>
  <strong>Word Usage:</strong>
  <%= @dictionary.wordUsage %>
</p>

<%= link_to 'Edit', edit_dictionary_path(@dictionary) %> |
<%= link_to 'Back', dictionaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Steadyfast</title>
    <%= csrf_meta_tags %>
    
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <style>
        .simple{
            width: 100%;
        }
        .simple table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
        }

        .simple td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        .simple tr:nth-child(even) {
            background-color: #dddddd;
        }
    
    </style>
        
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    

    
    
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    
    <%= favicon_link_tag asset_path('favicon-ship.png') %>

  </head>

  <body>
  

    <nav class="navbar navbar-default" style="background-color:#ff8d79;">
        <div class="container-fluid">
            <div class="navbar-header">     
                <a class="navbar-brand" href="#">Steadyfast</a>
            </div>          
            <ul id="nav-list" class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/work_space/index">Spelling</a></li>
                <li><a href="/dictionaries">Dictionary</a></li>
                <li><a href="/users">Users</a></li>
                <li><a href="/correctnesses">Correctnesses</a></li>
            </ul>
          
       </div>
    </nav>


    <%= yield %>
  </body>
</html>

app/views/sign_up/_form.html.erb
sign_up/create

<%= form_for(@user, url:sign_up_create_path) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :email  %>
    <%= f.text_field :email %>
  </div>
  
    <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :firstName, 'First Name' %>
    <%= f.text_field :firstName %>
  </div>

  <div class="field">
    <%= f.label :lastName, 'Last Name' %>
    <%= f.text_field :lastName %>
  </div>


  <div class="actions">
    <%= f.submit 'Sign Up', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/sign_up/index.html.erb
<h1>Sign Up</h1>

<%= render 'form', user: @user %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :email  %>
    <%= f.text_field :email %>
  </div>
  
    <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :firstName, 'First Name' %>
    <%= f.text_field :firstName %>
  </div>

  <div class="field">
    <%= f.label :lastName, 'Last Name' %>
    <%= f.text_field :lastName %>
  </div>

  <div class="field">
    <%= f.label :rights %>
    <%= f.text_field :rights %>
  </div>

  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="simple">
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Rights</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.firstName %></td>
        <td><%= user.lastName %></td>
        <td><%= user.rights %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.firstName %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.lastName %>
</p>

<p>
  <strong>Rights:</strong>
  <%= @user.rights %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
 <style>  
 /* sign in FORM */
#logreg-forms{
    width:412px;
    margin:10vh auto;
    background-color:#f3f3f3;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
  transition: all 0.3s cubic-bezier(.25,.8,.25,1);
}
#logreg-forms form {
    width: 100%;
    max-width: 410px;
    padding: 15px;
    margin: auto;
}
#logreg-forms .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
}
#logreg-forms .form-control:focus { z-index: 2; }
#logreg-forms .form-signin input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
}
#logreg-forms .form-signin input[type="password"] {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}

#logreg-forms .social-login{
    width:390px;
    margin:0 auto;
    margin-bottom: 14px;
}
#logreg-forms .social-btn{
    font-weight: 100;
    color:white;
    width:190px;
    font-size: 0.9rem;
}

#logreg-forms a{
    display: block;
    padding-top:10px;
    color:lightseagreen;
}

#logreg-form .lines{
    width:200px;
    border:1px solid red;
}


#logreg-forms button[type="submit"]{ margin-top:10px; }

#logreg-forms .facebook-btn{  background-color:#3C589C; }

#logreg-forms .google-btn{ background-color: #DF4B3B; }

#logreg-forms .form-reset, #logreg-forms .form-signup{ display: none; }

#logreg-forms .form-signup .social-btn{ width:210px; }

#logreg-forms .form-signup input { margin-bottom: 2px;}

.form-signup .social-login{
    width:210px !important;
    margin: 0 auto;
}

/* Mobile */

@media screen and (max-width:500px){
    #logreg-forms{
        width:300px;
    }
    
    #logreg-forms  .social-login{
        width:200px;
        margin:0 auto;
        margin-bottom: 10px;
    }
    #logreg-forms  .social-btn{
        font-size: 1.3rem;
        font-weight: 100;
        color:white;
        width:200px;
        height: 56px;
        
    }
    #logreg-forms .social-btn:nth-child(1){
        margin-bottom: 5px;
    }
    #logreg-forms .social-btn span{
        display: none;
    }
    #logreg-forms  .facebook-btn:after{
        content:'Facebook';
    }
  
    #logreg-forms  .google-btn:after{
        content:'Google+';
    }
    
}
 
 </style>
    
    
   <script src='https://kit.fontawesome.com/a076d05399.js'></script>
   
   <script type="text/javascript">
   
    $( document ).ready(function() {
        $('#nav-list').hide();
    });
   </script>
    
    <div id="logreg-forms">
        <form class="form-signin">
            <h1 class="h3 mb-3 font-weight-normal" style="text-align: center"> Sign in</h1>
            <div class="social-login">
                <button class="btn facebook-btn social-btn" type="button"><span><i class="fab fa-facebook-f"></i> Sign in with Facebook</span> </button>
                <button class="btn google-btn social-btn" type="button"><span><i class="fab fa-google-plus-g"></i> Sign in with Google+</span> </button>
            </div>
            <p style="text-align:center"> OR  </p>
            <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
            
            <button class="btn btn-success btn-block" type="submit"><i class="fas fa-sign-in-alt"></i> Sign in</button>
            <a href="#" id="forgot_pswd">Forgot password?</a>
            <hr>
            <!-- <p>Don't have an account!</p>  -->
            <button class="btn btn-primary btn-block" type="button" id="btn-signup"><i class="fas fa-user-plus"></i> <a href="/sign_up/index">Sign Up new Account</a></button>
            </form>

            <form action="/reset/password/" class="form-reset">
                <input type="email" id="resetEmail" class="form-control" placeholder="Email address" required="" autofocus="">
                <button class="btn btn-primary btn-block" type="submit">Reset Password</button>
                <a href="#" id="cancel_reset"><i class="fas fa-angle-left"></i> Back</a>
            </form>
            
            <form action="/signup/" class="form-signup">
                <div class="social-login">
                    <button class="btn facebook-btn social-btn" type="button"><span><i class="fab fa-facebook-f"></i> Sign up with Facebook</span> </button>
                </div>
                <div class="social-login">
                    <button class="btn google-btn social-btn" type="button"><span><i class="fab fa-google-plus-g"></i> Sign up with Google+</span> </button>
                </div>
                
                <p style="text-align:center">OR</p>

                <input type="text" id="user-name" class="form-control" placeholder="Full name" required="" autofocus="">
                <input type="email" id="user-email" class="form-control" placeholder="Email address" required autofocus="">
                <input type="password" id="user-pass" class="form-control" placeholder="Password" required autofocus="">
                <input type="password" id="user-repeatpass" class="form-control" placeholder="Repeat Password" required autofocus="">

                <button class="btn btn-primary btn-block" type="submit"><i class="fas fa-user-plus"></i> <a href="/sign_up/index">Sign Up</a> </button>
                <a href="#" id="cancel_signup"><i class="fas fa-angle-left"></i> Back</a>
            </form>
            <br>
            
    </div>
    
    

app/views/work_space/index.html.erb
<h1>Spelling Test</h1>
	<br>
    <div>
		<b>Message: </b><p id="message-answer"> </p>
	</div>
	
	<br>
	<div>
		<b>Count: </b><p id="message-count"> </p>
	</div>

	<br>
		<input type="text" id="answer" style="font-size: 45px;" >
		
	<br>
	<br>
	<div style="display:inline-block;" >
		<button type="button" class="btn btn-primary" onclick="previous()" >Previous</button>
		<button type="button" class="btn btn-primary" onclick="say()" >Say</button>
		<button type="button" class="btn btn-primary" onclick="check()" >Check</button>
		<button type="button" class="btn btn-primary" onclick="showDefine()" >Show Definition</button>
		<button type="button" class="btn btn-primary" onclick="show()" >Show</button>
		<button type="button" class="btn btn-primary" onclick="next()" >Next</button>
	</div>

	<br>
	<br>
	<div>
		<b>Word: </b><p id="word"> </p>
		<b>Part of Speech: </b><p id="part-of-speech"> </p>
		<b>Definition: </b><p id="definition"> </p>
		<b>Word Usage: </b><p id="word-usage"> </p>
		<b>Total Try Count: </b><p id="total-try-count"> </p>
		<b>Right Count: </b><p id="right-count"> </p>
	</div>